"use client";
import { useEffect,useMemo,useState } from "react";
import { Activity,LoaderCircle,RefreshCcw,Target } from "lucide-react";
import { PageIntro } from "@/components/intelligence-ui";

export default function MovesPage(){
  const[rows,setRows]=useState<any[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
  async function load(){const r=await fetch("/api/radar/moves",{cache:"no-store"});const d=await r.json();if(r.ok)setRows(Array.isArray(d)?d:[]);setLoading(false)}
  useEffect(()=>{load()},[]);
  async function correlate(){setBusy(true);setMessage("Correlating independent signals into strategic Moves...");try{const r=await fetch("/api/radar/moves",{method:"POST"});const d=await r.json();if(!r.ok)throw new Error(d.error||"Correlation failed");setMessage(`${d.moves||0} strategic pattern${d.moves===1?"":"s"} detected or refreshed.`);await load()}catch(e){setMessage(e instanceof Error?e.message:"Correlation failed")}finally{setBusy(false)}}
  async function generateDecision(id:string){setMessage("Building an evidence-backed decision memo...");const r=await fetch("/api/radar/decisions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({moveId:id})});const d=await r.json();setMessage(r.ok?"Decision memo created. Open Decisions to review it.":d.error||"Could not create decision.")}
  const stats=useMemo(()=>({active:rows.filter(r=>["watching","confirmed"].includes(r.status)).length,confirmed:rows.filter(r=>r.status==="confirmed").length,avg:rows.length?Math.round(rows.reduce((a,r)=>a+Number(r.confidence||0),0)/rows.length):0,high:rows.filter(r=>Number(r.impact_score||0)>=75).length}),[rows]);
  return <div className="content">
    <PageIntro eyebrow="CORRELATION ENGINE" title="RADAR Moves" description="RADAR connects multiple independent signals into coherent strategic developments instead of flooding you with isolated alerts." action={<button className="primary-button" onClick={correlate} disabled={busy}>{busy?<LoaderCircle size={14}/>:<RefreshCcw size={14}/>} {busy?"Correlating...":"Correlate signals"}</button>}/>
    {message?<div className="competition-live-message" style={{marginBottom:12}}>{message}</div>:null}
    <section className="metrics-grid"><div className="stat-tile"><span>Active Moves</span><strong>{stats.active}</strong><small>{stats.confirmed} confirmed</small></div><div className="stat-tile"><span>Confirmed</span><strong>{stats.confirmed}</strong><small>Multi-signal pattern</small></div><div className="stat-tile"><span>Avg confidence</span><strong>{stats.avg}%</strong><small>Across current Moves</small></div><div className="stat-tile"><span>High impact</span><strong>{stats.high}</strong><small>Founder attention</small></div></section>
    <section style={{display:"grid",gap:12}}>{loading?<div className="panel" style={{padding:24}}>Loading Moves...</div>:rows.length?rows.map(m=><article key={m.id} className="panel founder-panel"><div className="founder-panel-head"><div><span>{m.move_type?.replaceAll("_"," ")} · {m.status}</span><h2>{m.title}</h2></div><Activity size={20}/></div><p>{m.summary}</p><div className="founder-list-rows"><div><strong>{m.competitor?.name||"Competitor"}</strong><span>{m.signal_count||0} supporting signals</span></div><div><strong>{Math.round(Number(m.impact_score||0))}% impact</strong><span>{Math.round(Number(m.confidence||0))}% confidence</span></div></div><div className="founder-action-block"><span>WHY RADAR THINKS THIS IS A MOVE</span><strong>{m.rationale}</strong></div><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:12,marginTop:14}}><span style={{fontSize:11,color:"#737a80"}}>{m.recommended_action}</span><button className="secondary-button" onClick={()=>generateDecision(m.id)}><Target size={14}/>Create decision</button></div></article>):<div className="panel" style={{padding:28,textAlign:"center",color:"#737a80"}}>No strategic Move is strong enough yet. RADAR needs multiple related signals before it promotes a pattern.</div>}</section>
  </div>
}
