"use client";

import { useEffect, useMemo, useState } from "react";
import { Activity, BellRing, Clock3, Database, ExternalLink, LoaderCircle, Save, ShieldCheck } from "lucide-react";
import { PageIntro } from "@/components/intelligence-ui";

export default function SourcesPage(){
  const [data,setData]=useState<any>(null);const [alerts,setAlerts]=useState<any>(null);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [message,setMessage]=useState("");
  async function load(){setLoading(true);try{const [a,b]=await Promise.all([fetch("/api/radar/sources",{cache:"no-store"}),fetch("/api/radar/alerts",{cache:"no-store"})]);const [x,y]=await Promise.all([a.json(),b.json()]);setData(x);setAlerts(y)}finally{setLoading(false)}}
  useEffect(()=>{load();const t=window.setInterval(load,30000);return()=>window.clearInterval(t)},[]);
  async function saveAlerts(){if(!alerts)return;setSaving(true);setMessage("");try{const r=await fetch("/api/radar/alerts",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(alerts)});const d=await r.json();if(!r.ok)throw new Error(d.error||"Could not save alert settings");setAlerts(d);setMessage("Alert preferences saved.")}catch(e){setMessage(e instanceof Error?e.message:"Could not save alert settings")}finally{setSaving(false)}}
  async function runMaintenance(){setMessage("Checking due sources and semantic changes...");try{const r=await fetch("/api/radar/maintenance",{method:"POST"});const d=await r.json();if(!r.ok)throw new Error(d.error||"Maintenance failed");setMessage(`Checked ${d.source_monitor?.checked||0} sources · ${d.source_monitor?.changed||0} changed · ${d.source_monitor?.signals||0} new signals.`);await load()}catch(e){setMessage(e instanceof Error?e.message:"Maintenance failed")}}

  const metrics=useMemo(()=>{const monitors=data?.monitors||[],sources=data?.sources||[],competitors=data?.competitors||[],health=data?.health||{};return{sources:sources.length,active:monitors.filter((m:any)=>m.status==="active").length,covered:competitors.filter((c:any)=>sources.some((s:any)=>s.competitor_id===c.id&&s.status==="active")).length,errors:health.error||0,snapshots:health.snapshots||0,changed:health.changed_24h||0}},[data]);
  return <div className="content">
    <PageIntro eyebrow="MONITORING CONTROL" title="Sources & Alerts" description="RADAR now keeps source history, checks source health, compares snapshots and turns only meaningful business changes into intelligence." action={<button className="secondary-button" onClick={runMaintenance}><Activity size={14}/> Check sources now</button>}/>
    <section className="metrics-grid"><div className="stat-tile"><span>Tracked sources</span><strong>{metrics.sources}</strong><small>First-party and evidence URLs</small></div><div className="stat-tile"><span>Snapshots</span><strong>{metrics.snapshots}</strong><small>Historical source states</small></div><div className="stat-tile"><span>Changed 24h</span><strong>{metrics.changed}</strong><small>Meaningful or pending review</small></div><div className="stat-tile"><span>Source errors</span><strong>{metrics.errors}</strong><small>Needs attention</small></div></section>

    <section className="founder-two-col">
      <article className="panel founder-panel"><div className="founder-panel-head"><div><span>SEMANTIC SOURCE REGISTRY</span><h2>What RADAR is actually checking</h2></div><Database size={20}/></div>{loading?<p>Loading source health...</p>:(data?.sources||[]).length?<div className="founder-list-rows">{data.sources.slice(0,40).map((s:any)=><div key={s.id}><strong>{s.competitor?.name||s.title||s.url}</strong><span>{s.health} · {s.snapshot_count||0} snapshots · every {s.check_frequency_minutes||360} min{s.last_changed_at?` · changed ${new Date(s.last_changed_at).toLocaleString()}`:""}{s.last_error?` · ${s.last_error}`:""}</span></div>)}</div>:<p>No semantic sources registered yet. RADAR adds them from verified competitors and evidence.</p>}</article>
      <article className="panel founder-panel"><div className="founder-panel-head"><div><span>RECURRING INTELLIGENCE</span><h2>Automatic jobs</h2></div><Clock3 size={20}/></div><div className="founder-list-rows">{(data?.recurring_tasks||[]).length?data.recurring_tasks.map((t:any)=><div key={t.task_key}><strong>{String(t.task_key).replaceAll("_"," ").replaceAll("."," ")}</strong><span>Every {t.interval_minutes} min · next {t.next_run_at?new Date(t.next_run_at).toLocaleString():"pending"}{t.last_error?` · error: ${t.last_error}`:""}</span></div>):<div><strong>No recurring tasks yet</strong><span>They are created automatically during maintenance.</span></div>}</div></article>
    </section>

    <section className="founder-two-col" style={{marginTop:13}}>
      <article className="panel founder-panel"><div className="founder-panel-head"><div><span>PROVIDER MONITORS</span><h2>Live web watches</h2></div><Activity size={20}/></div>{(data?.monitors||[]).length?<div className="founder-list-rows">{data.monitors.map((m:any)=><div key={m.id}><strong>{m.competitor?.name||m.name}</strong><span>{m.monitor_type} · {m.status} · {m.schedule_text}{m.last_error?` · ${m.last_error}`:""}</span></div>)}</div>:<p>No provider monitors yet.</p>}</article>
      <article className="panel founder-panel"><div className="founder-panel-head"><div><span>SOURCE MIX</span><h2>Evidence by source type</h2></div><ShieldCheck size={20}/></div><div className="founder-list-rows">{data?.source_types&&Object.keys(data.source_types).length?Object.entries(data.source_types).map(([type,count]:any)=><div key={type}><strong>{String(type).replaceAll("_"," ")}</strong><span>{count} evidence item{Number(count)===1?"":"s"}</span></div>):<div><strong>No source history yet</strong><span>Evidence types appear after discovery and monitoring.</span></div>}</div></article>
    </section>

    <section className="panel founder-panel founder-wide-panel" style={{marginTop:13}}><div className="founder-panel-head"><div><span>ALERT RULES</span><h2>Only interrupt me when it matters.</h2></div><BellRing size={20}/></div>{alerts?<div className="startup-form-grid"><label><span>Minimum impact</span><input type="number" min="0" max="100" value={alerts.min_impact??70} onChange={e=>setAlerts({...alerts,min_impact:Number(e.target.value)})}/></label><label><span>Minimum confidence</span><input type="number" min="0" max="100" value={alerts.min_confidence??70} onChange={e=>setAlerts({...alerts,min_confidence:Number(e.target.value)})}/></label><label><span>New competitor threshold</span><input type="number" min="0" max="100" value={alerts.new_competitor_threshold??55} onChange={e=>setAlerts({...alerts,new_competitor_threshold:Number(e.target.value)})}/></label><label><span>Delivery</span><select value={alerts.delivery_mode||"digest"} onChange={e=>setAlerts({...alerts,delivery_mode:e.target.value})} style={{height:42,border:"1px solid #d8dcdf",borderRadius:9,padding:"0 10px",background:"white"}}><option value="digest">Digest</option><option value="immediate">Immediate</option></select></label><label style={{display:"flex",alignItems:"center",gap:8}}><input type="checkbox" checked={Boolean(alerts.email_enabled)} onChange={e=>setAlerts({...alerts,email_enabled:e.target.checked})}/><span>Email alerts enabled</span></label><label style={{display:"flex",alignItems:"center",gap:8}}><input type="checkbox" checked={Boolean(alerts.include_high_threat_only)} onChange={e=>setAlerts({...alerts,include_high_threat_only:e.target.checked})}/><span>Only high-threat companies</span></label></div>:<p>Loading alert preferences...</p>}<div style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"center",marginTop:14}}><span style={{fontSize:11,color:"#737a80"}}>{message||"Semantic monitoring filters cosmetic noise before creating signals."}</span><button className="primary-button" onClick={saveAlerts} disabled={!alerts||saving}>{saving?<LoaderCircle size={14}/>:<Save size={14}/>} {saving?"Saving...":"Save alerts"}</button></div></section>

    <section className="panel founder-panel founder-wide-panel" style={{marginTop:13}}><div className="founder-panel-head"><div><span>RECENT EVIDENCE</span><h2>Trace intelligence back to source</h2></div><ExternalLink size={20}/></div><div style={{display:"grid",gap:0}}>{(data?.evidence||[]).slice(0,30).map((e:any)=><a key={e.id} href={e.source_url||"#"} target="_blank" rel="noreferrer" style={{display:"grid",gridTemplateColumns:"1fr auto",gap:12,padding:"12px 0",borderBottom:"1px solid #e3e6e8",textDecoration:"none"}}><div><strong style={{display:"block",fontSize:13,color:"#202428"}}>{e.title||e.source_type||"Public source"}</strong><span style={{fontSize:11,color:"#7a8085"}}>{e.source_url||"Source URL unavailable"}</span></div><span style={{fontSize:11,color:"#7a8085"}}>{Math.round(Number(e.confidence||0))}% confidence</span></a>)}{!loading&&!(data?.evidence||[]).length?<p>No source evidence yet.</p>:null}</div></section>
  </div>;
}
