"use client";
import { FormEvent,useEffect,useMemo,useState } from "react";
import { useSearchParams } from "next/navigation";
import { LoaderCircle,Plus } from "lucide-react";
import { PageIntro } from "@/components/intelligence-ui";

export default function OutcomesPage(){
  const params=useSearchParams();const presetDecision=params.get("decision")||"",presetAction=params.get("action")||"";
  const[rows,setRows]=useState<any[]>([]),[decisions,setDecisions]=useState<any[]>([]),[actions,setActions]=useState<any[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[decisionId,setDecisionId]=useState(presetDecision),[actionId,setActionId]=useState(presetAction),[result,setResult]=useState(""),[impact,setImpact]=useState(70),[assessment,setAssessment]=useState(""),[message,setMessage]=useState("");
  async function load(){const[o,d,a]=await Promise.all([fetch("/api/radar/outcomes",{cache:"no-store"}),fetch("/api/radar/decisions",{cache:"no-store"}),fetch("/api/radar/actions",{cache:"no-store"})]);const[od,dd,ad]=await Promise.all([o.json(),d.json(),a.json()]);if(o.ok)setRows(Array.isArray(od)?od:[]);if(d.ok)setDecisions(Array.isArray(dd)?dd:[]);if(a.ok)setActions(Array.isArray(ad)?ad:[]);setLoading(false)}
  useEffect(()=>{load()},[]);
  async function submit(e:FormEvent){e.preventDefault();if(!decisionId||!result.trim())return;setSaving(true);setMessage("");try{const r=await fetch("/api/radar/outcomes",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({decisionId,actionId:actionId||null,result,impact,assessment})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Could not record outcome");setResult("");setAssessment("");setMessage("Outcome recorded. RADAR now has execution memory for this decision.");await load()}catch(e){setMessage(e instanceof Error?e.message:"Could not record outcome")}finally{setSaving(false)}}
  const stats=useMemo(()=>({logged:rows.length,positive:rows.filter(r=>Number(r.impact||0)>=70).length,mixed:rows.filter(r=>Number(r.impact||0)>=40&&Number(r.impact||0)<70).length,negative:rows.filter(r=>r.impact!=null&&Number(r.impact)<40).length}),[rows]);
  return <div className="content">
    <PageIntro eyebrow="LEARNING LOOP" title="Outcomes" description="Record what actually happened after a strategic decision. This is the final link in RADAR's Evidence → Signal → Move → Decision → Action → Outcome loop."/>
    <section className="metrics-grid"><div className="stat-tile"><span>Logged</span><strong>{stats.logged}</strong><small>Execution memories</small></div><div className="stat-tile"><span>Positive</span><strong>{stats.positive}</strong><small>Impact ≥70</small></div><div className="stat-tile"><span>Mixed</span><strong>{stats.mixed}</strong><small>Impact 40–69</small></div><div className="stat-tile"><span>Negative</span><strong>{stats.negative}</strong><small>Useful learning</small></div></section>
    <form onSubmit={submit} className="panel founder-panel" style={{marginBottom:13}}><div className="founder-panel-head"><div><span>RECORD OUTCOME</span><h2>What actually happened?</h2></div><Plus size={20}/></div><div className="startup-form-grid"><label><span>Decision</span><select required value={decisionId} onChange={e=>setDecisionId(e.target.value)} style={{height:42,border:"1px solid #d8dcdf",borderRadius:9,padding:"0 10px",background:"white"}}><option value="">Choose decision</option>{decisions.filter(d=>d.status!=="dismissed").map(d=><option key={d.id} value={d.id}>{d.title}</option>)}</select></label><label><span>Action</span><select value={actionId} onChange={e=>setActionId(e.target.value)} style={{height:42,border:"1px solid #d8dcdf",borderRadius:9,padding:"0 10px",background:"white"}}><option value="">No linked action</option>{actions.filter(a=>!decisionId||a.decision_id===decisionId).map(a=><option key={a.id} value={a.id}>{a.title}</option>)}</select></label><label style={{gridColumn:"1 / -1"}}><span>Result</span><input required value={result} onChange={e=>setResult(e.target.value)} placeholder="What changed after the decision?"/></label><label><span>Impact score</span><input type="number" min="0" max="100" value={impact} onChange={e=>setImpact(Number(e.target.value))}/></label><label><span>Assessment</span><input value={assessment} onChange={e=>setAssessment(e.target.value)} placeholder="What did we learn?"/></label></div><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:12,marginTop:14}}><span style={{fontSize:11,color:"#737a80"}}>{message||"Use an honest impact score. Negative results are valuable training data for future decisions."}</span><button className="primary-button" disabled={saving||!decisionId||!result.trim()}>{saving?<LoaderCircle size={14}/>:<Plus size={14}/>} {saving?"Saving...":"Record outcome"}</button></div></form>
    <section className="radar-outcome-list">{loading?<div className="panel" style={{padding:24}}>Loading outcomes...</div>:rows.length?rows.map(o=><div className="radar-outcome-row" key={o.id}><span>{o.decision?.title||"Decision outcome"}</span><strong>{o.result}</strong><em>{o.impact==null?"No score":`${Math.round(Number(o.impact))}% impact`}</em></div>):<div className="panel" style={{padding:28,textAlign:"center",color:"#737a80"}}>No outcomes recorded yet. Complete an Action, then tell RADAR what happened.</div>}</section>
  </div>
}
