"use client";

import Link from "next/link";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { ArrowUpRight, LoaderCircle, Plus, Search, ShieldCheck, X } from "lucide-react";
import { PageIntro } from "@/components/intelligence-ui";

type Competitor = any;

export default function CompaniesPage(){
  const [rows,setRows]=useState<Competitor[]>([]); const [query,setQuery]=useState(""); const [loading,setLoading]=useState(true); const [scanning,setScanning]=useState(false); const [message,setMessage]=useState("");
  const [adding,setAdding]=useState(false); const [showAdd,setShowAdd]=useState(false); const [name,setName]=useState(""); const [website,setWebsite]=useState(""); const [monitoring,setMonitoring]=useState(false);
  async function load(silent=false){try{const r=await fetch("/api/radar/competitors",{cache:"no-store"});const d=await r.json();if(r.ok)setRows(Array.isArray(d)?d:[])}finally{if(!silent)setLoading(false)}}
  useEffect(()=>{load();const timer=window.setInterval(()=>load(true),8000);const onFocus=()=>load(true);window.addEventListener("focus",onFocus);return()=>{window.clearInterval(timer);window.removeEventListener("focus",onFocus)}},[]);
  async function rescan(){setScanning(true);setMessage("Finding real companies and the specific products that overlap with your startup...");try{const r=await fetch("/api/radar/discover",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({force:true})});const d=await r.json();setMessage(r.ok?`${d.inspected||0} sources inspected · ${d.entities_extracted||0} company entities extracted · ${d.promoted||0} verified product competitors added`:d.error||"Scan failed");await load()}catch{setMessage("Discovery failed. Please try again.")}finally{setScanning(false)}}
  async function addCompetitor(e:FormEvent){e.preventDefault();if(!website.trim())return;setAdding(true);setMessage("");try{const r=await fetch("/api/radar/competitors",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,website})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Could not add competitor");await load();setName("");setWebsite("");setShowAdd(false);setMessage("Competitor added. Open its dossier to scan the specific overlapping product.")}catch(e){setMessage(e instanceof Error?e.message:"Could not add competitor")}finally{setAdding(false)}}
  async function monitorTop(){const targets=[...rows].filter(c=>!c.monitor_active&&c.website).sort((a,b)=>Number(b.threat_score||0)-Number(a.threat_score||0)).slice(0,5);if(!targets.length){setMessage("Your highest-priority competitors are already monitored, or none are ready yet.");return}setMonitoring(true);let ok=0;await Promise.all(targets.map(async c=>{try{const r=await fetch(`/api/radar/competitors/${c.id}/monitor`,{method:"POST"});if(r.ok)ok++}catch{}}));await load();setMessage(`${ok} competitor monitor${ok===1?"":"s"} activated.`);setMonitoring(false)}
  const filtered=useMemo(()=>rows.filter(c=>`${c.name} ${c.related_product||""} ${c.description||""} ${c.category}`.toLowerCase().includes(query.toLowerCase())),[rows,query]);
  const core=rows.filter(c=>Number(c.product_overlap_score||0)>=70||Number(c.similarity_score||0)>=75).length; const scanned=rows.filter(c=>c.last_scanned_at).length; const monitored=rows.filter(c=>c.monitor_active).length;
  return <div className="content">
    <PageIntro eyebrow="PRODUCT-LEVEL COMPETITIVE UNIVERSE" title="Competitors" description="RADAR identifies real companies, the specific product that overlaps with yours, verifies product similarity from first-party evidence, and ranks threat." action={<div style={{display:"flex",gap:8,flexWrap:"wrap"}}><button onClick={()=>setShowAdd(v=>!v)} className="secondary-button">{showAdd?<X size={14}/>:<Plus size={14}/>} {showAdd?"Close":"Add competitor"}</button><button onClick={monitorTop} disabled={monitoring||!rows.length} className="secondary-button">{monitoring?<LoaderCircle size={14}/>:<ShieldCheck size={14}/>} {monitoring?"Activating...":"Monitor top 5"}</button><button onClick={rescan} disabled={scanning} className="primary-button">{scanning?<><LoaderCircle size={14}/>Scanning...</>:"Scan market now"}</button></div>}/>
    {showAdd?<form onSubmit={addCompetitor} className="panel" style={{padding:16,marginBottom:12,display:"grid",gridTemplateColumns:"1fr 1.5fr auto",gap:10,alignItems:"end"}}><label style={{display:"grid",gap:6,fontSize:11,color:"#666"}}><span>Company name</span><input value={name} onChange={e=>setName(e.target.value)} placeholder="Optional" style={{height:42,border:"1px solid #dce0e3",borderRadius:9,padding:"0 11px"}}/></label><label style={{display:"grid",gap:6,fontSize:11,color:"#666"}}><span>Website</span><input value={website} onChange={e=>setWebsite(e.target.value)} placeholder="competitor.com" required style={{height:42,border:"1px solid #dce0e3",borderRadius:9,padding:"0 11px"}}/></label><button className="primary-button" disabled={adding} style={{height:42}}>{adding?<LoaderCircle size={14}/>:<Plus size={14}/>} {adding?"Adding...":"Add"}</button></form>:null}
    {message?<div className="competition-live-message" style={{marginBottom:12}}>{message}</div>:null}
    <section className="metrics-grid"><div className="stat-tile"><span>Tracked</span><strong>{rows.length}</strong><small>Verified company entities</small></div><div className="stat-tile"><span>Core product threats</span><strong>{core}</strong><small>High product overlap</small></div><div className="stat-tile"><span>Monitored</span><strong>{monitored}</strong><small>Continuous watches</small></div><div className="stat-tile"><span>Deep-scanned</span><strong>{scanned}</strong><small>First-party evidence verified</small></div></section>
    <article className="panel" style={{padding:18}}>
      <div style={{display:"flex",alignItems:"center",gap:10,border:"1px solid #dde1e4",borderRadius:10,padding:"0 12px",height:44,marginBottom:14}}><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search company or related product..." style={{border:0,outline:"none",width:"100%",fontSize:13,background:"transparent"}}/></div>
      {loading?<div style={{padding:20,color:"#747b81"}}>Loading competitors...</div>:filtered.length?<div className="intel-table-wrap"><div className="intel-table-head" style={{gridTemplateColumns:"1.55fr 1.4fr .6fr .6fr .6fr"}}><span>Company</span><span>Related product</span><span>Product overlap</span><span>Threat</span><span>Status</span></div>{filtered.map(c=><Link href={`/companies/${c.id}`} className="intel-table-row" style={{gridTemplateColumns:"1.55fr 1.4fr .6fr .6fr .6fr",textDecoration:"none"}} key={c.id}><div className="signal-main"><div><span className="signal-company">{c.category}</span></div><strong>{c.name}</strong><small>{c.relationship_reason||c.description||c.website}</small></div><div className="signal-main"><strong>{c.related_product||"Product being verified"}</strong><small>{Number(c.relation_confidence||0)}% relationship confidence</small></div><strong>{Math.round(Number(c.product_overlap_score||0))}%</strong><strong>{Math.round(Number(c.threat_score||0))}%</strong><span className="age-cell">{c.monitor_active?"monitoring":c.last_scanned_at?"verified":"provisional"}<ArrowUpRight size={13}/></span></Link>)}</div>:<div style={{padding:30,textAlign:"center",color:"#737a80",lineHeight:1.7}}><LoaderCircle size={18} style={{margin:"0 auto 8px"}}/><strong style={{display:"block",color:"#4f565b",marginBottom:3}}>RADAR is resolving real companies and their competing products.</strong>Articles and directories are used as sources only. They are not listed as competitors.</div>}
    </article>
  </div>;
}
